{% set name = "geojson-rewind" %}
{% set version = "1.2.1" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name.replace('-', '_') }}-{{ version }}.tar.gz
  sha256: 1b7b8b3714eb1f0cfccdba023444f0073be2c9ce148d72c69fd097ea7743da60

build:
  number: 0
  noarch: python
  entry_points:
    - rewind = geojson_rewind.rewind:main
  script:
    - {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - poetry >=1.0.2
    - python {{ python_min }}
  run:
    - python >={{ python_min }}

test:
  imports:
    - geojson_rewind
  commands:
    - pip check
    - rewind --help
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/chris48s/geojson-rewind
  summary: A Python library for enforcing polygon ring winding order in GeoJSON
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - thewchan
