{% set name = "geojson-rewind" %}
{% set version = "1.0.2" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/geojson-rewind-{{ version }}.tar.gz
  sha256: 3ba2c88b99855c6b8201834a476e7041fb04b377d4e5c1f3fb293daeac00f717

build:
  number: 0
  noarch: python
  entry_points:
    - rewind = geojson_rewind.rewind:main
  script:
    # Removing pyproject.toml here due to pip bug
    - {{ PYTHON }} -c "__import__('os').unlink('pyproject.toml')"
    - {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - poetry
    - python >=3.6
  run:
    - python >=3.6

test:
  imports:
    - geojson_rewind
  commands:
    - pip check
    - rewind --help
  requires:
    - pip

about:
  home: https://github.com/chris48s/geojson-rewind
  summary: A Python library for enforcing polygon ring winding order in GeoJSON
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - thewchan
