schema_version: 1

context:
  name: geojson-rewind
  version: 1.2.1

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/${{ name[0] }}/${{ name }}/${{ name | replace('-', '_') }}-${{ version }}.tar.gz
  sha256: 1b7b8b3714eb1f0cfccdba023444f0073be2c9ce148d72c69fd097ea7743da60

build:
  number: 0
  noarch: python
  script:
    - ${{ PYTHON }} -m pip install . -vv
  python:
    entry_points:
      - rewind = geojson_rewind.rewind:main

requirements:
  host:
    - pip
    - poetry-core >=2.0.0,<3.0.0
    - python ${{ python_min }}.*
  run:
    - python >=${{ python_min }}

tests:
  - python:
      imports:
        - geojson_rewind
      pip_check: true
      python_version: ${{ python_min }}
  - requirements:
      run:
        - python ${{ python_min }}.*
    script:
      - rewind --help

about:
  summary: A Python library for enforcing polygon ring winding order in GeoJSON
  license: MIT
  license_file: LICENSE
  homepage: https://github.com/chris48s/geojson-rewind

extra:
  recipe-maintainers:
    - thewchan
